### ISSUE TITLE
firestore and storage support added to Windows

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutterfire#9]
https://github.com/firebase/flutterfire/discussions/5557#discussioncomment-7371323

Can we benefit from it? Any difference with our current implementation (firebase_storage_tizen)?

**Comment by daeyeon** [comment]
We're using modified the firebase_storage code of the SDK due to the lack of core features like file listing. Upgrading to the new SDK would remove such fixes and improve reliability.
